name: Build StreamVorti with Spack

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-with-spack:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install minimal system prerequisites for Spack
      run: ./scripts/build-with-spack/01-install-spack-prerequisites.sh


    - name: Cache Spack installation
      id: cache-spack
      uses: actions/cache@v3
      if: always()
      with:
        path: ~/spack
        key: spack-installation-${{ runner.os }}-v1
        restore-keys: |
          spack-installation-${{ runner.os }}-

    - name: Install Spack
      if: steps.cache-spack.outputs.cache-hit != 'true'
      run: ./scripts/build-with-spack/02-install-spack.sh ~/spack

    - name: Configure Spack
      run: ./scripts/build-with-spack/03-configure-spack.sh ~/spack

    - name: Cache Spack packages and environment
      uses: actions/cache@v3
      if: always()
      with:
        path: |
          ~/spack/var/spack/cache
          ~/spack/opt/spack
          ~/spack/var/spack/environments/streamvorti
        key: spack-env-streamvorti-${{ runner.os }}-v1
        restore-keys: |
          spack-env-streamvorti-${{ runner.os }}-

    - name: Create and install Spack environment
      run: ./scripts/build-with-spack/04-create-spack-environment.sh ~/spack streamvorti spack.yaml

    - name: Show Spack environment info
      if: always()
      run: ./scripts/build-with-spack/05-show-spack-environment.sh ~/spack streamvorti

    - name: Inspect MFEM Installation
      run: ./scripts/build-with-spack/06-inspect-mfem-installation.sh ~/spack streamvorti

    - name: Build StreamVorti
      run: ./scripts/build-with-spack/07-build-streamvorti.sh ~/spack streamvorti Release

    - name: Run tests
      run: ./scripts/build-with-spack/08-run-ctest.sh ~/spack streamvorti build

    - name: Check built artifacts
      run: ./scripts/build-with-spack/09-check-built-artifacts.sh build

    - name: Run test examples
      run: ./scripts/build-with-spack/10-run-example-tests.sh ~/spack streamvorti "$GITHUB_WORKSPACE/build/MfemRun" "$GITHUB_WORKSPACE/build/StreamVorti"
