name: Build StreamVorti with Spack

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-with-spack:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install minimal system prerequisites for Spack
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ca-certificates \
          coreutils \
          curl \
          environment-modules \
          gfortran \
          git \
          gpg \
          lsb-release \
          python3 \
          python3-venv \
          unzip \
          zip


    - name: Cache Spack installation
      id: cache-spack
      uses: actions/cache@v3
      if: always()
      with:
        path: ~/spack
        key: spack-${{ runner.os }}-${{ hashFiles('.github/workflows/build-spack.yml') }}
        restore-keys: |
          spack-${{ runner.os }}-

    - name: Install Spack
      if: steps.cache-spack.outputs.cache-hit != 'true'
      run: |
        git clone -c feature.manyFiles=true https://github.com/spack/spack.git ~/spack
        echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc

    - name: Configure Spack
      run: |
        source ~/spack/share/spack/setup-env.sh

        # Configure Spack to use system compilers
        spack compiler find

        # Add binary mirror for faster installs
        spack mirror add binary_mirror https://binaries.spack.io/releases/v0.21
        spack buildcache keys --install --trust

    - name: Cache Spack packages
      uses: actions/cache@v3
      if: always()
      with:
        path: |
          ~/spack/var/spack/cache
          ~/spack/opt/spack
        key: spack-packages-${{ runner.os }}-${{ hashFiles('.github/workflows/build-spack.yml') }}
        restore-keys: |
          spack-packages-${{ runner.os }}-

    - name: Install all dependencies with Spack
      run: |
        source ~/spack/share/spack/setup-env.sh

        # Install MFEM 4.8 with all required features
        spack install mfem@4.8 \
          +mpi \
          +metis \
          +lapack \
          +zlib \
          ^openmpi \
          ^hypre+mpi \
          ^metis+int64 \
          ^suite-sparse

        # Install additional dependencies for StreamVorti
        spack install cgal@6.0
        spack install eigen@3.4
        spack install cmake@3.31

        # Load all the modules
        spack load mfem
        spack load cgal
        spack load eigen
        spack load openmpi
        spack load suite-sparse
        spack load cmake@3.31

    - name: Build StreamVorti
      run: |
        source ~/spack/share/spack/setup-env.sh

        # Load all required modules
        spack load cmake@3.31
        spack load mfem
        spack load cgal
        spack load eigen
        spack load openmpi
        spack load suite-sparse

        # Get installation paths
        MFEM_DIR=$(spack location -i mfem)
        echo "MFEM_DIR=$MFEM_DIR"

        # Find MFEM cmake config directory
        MFEM_CMAKE_DIR=$(find $MFEM_DIR -name "MFEMConfig.cmake" -o -name "mfem-config.cmake" 2>/dev/null | head -n1 | xargs -r dirname)
        if [ -z "$MFEM_CMAKE_DIR" ]; then
          # Try common locations
          if [ -d "$MFEM_DIR/lib/cmake/mfem" ]; then
            MFEM_CMAKE_DIR="$MFEM_DIR/lib/cmake/mfem"
          elif [ -d "$MFEM_DIR/share/mfem" ]; then
            MFEM_CMAKE_DIR="$MFEM_DIR/share/mfem"
          else
            echo "ERROR: Could not find MFEM cmake config directory"
            echo "Contents of MFEM_DIR:"
            ls -la $MFEM_DIR
            exit 1
          fi
        fi
        echo "MFEM_CMAKE_DIR=$MFEM_CMAKE_DIR"

        # Create build directory
        mkdir build
        cd build

        # Configure with CMake from Spack
        cmake \
          -Dmfem_DIR=$MFEM_CMAKE_DIR \
          -DMFEM_DIR=$MFEM_DIR \
          -DCMAKE_BUILD_TYPE=Release \
          ..

        # Build
        make -j$(nproc) VERBOSE=1

    - name: Run tests
      run: |
        source ~/spack/share/spack/setup-env.sh
        spack load mfem
        spack load cgal
        spack load eigen
        spack load openmpi

        cd build
        ctest --output-on-failure || true

    - name: Check built artifacts
      run: |
        echo "Checking built executables and libraries:"
        ls -la build/
        ls -la build/lib/StreamVorti/ || true

        if [ -f build/MfemRun ]; then
          echo "MfemRun executable built successfully"
          ldd build/MfemRun
        else
          echo "WARNING: MfemRun executable not found"
        fi

        if [ -f build/StreamVorti ]; then
          echo "StreamVorti executable built successfully"
          ldd build/StreamVorti
        else
          echo "WARNING: StreamVorti executable not found"
        fi

        if [ -f build/lib/StreamVorti/libStreamVorti_static.a ]; then
          echo "StreamVorti static library built successfully"
          file build/lib/StreamVorti/libStreamVorti_static.a
        else
          echo "WARNING: StreamVorti static library not found"
        fi

    - name: Show Spack environment info
      if: always()
      run: |
        source ~/spack/share/spack/setup-env.sh
        echo "=== Spack Specs ==="
        spack find
        echo "=== Loaded Modules ==="
        spack find --loaded
        echo "=== MFEM Configuration ==="
        spack spec mfem || true